# This is a basic workflow to help you get started with Actions

name: Build web

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:	ubuntu-20.04
    env:
      LANG: en_US.UTF-8
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: cd $GITHUB_WORKSPACE
      
    - name: Prerequisites
      run: sudo apt-get install -yy pandoc pandoc-citeproc python3-bibtexparser
    
    - name: Checkout pages
      run: |
        git worktree add ../build gh-pages
        rm ../build/* ../build/.gitignore -rf
        ln -s ../build _build

    - name: Build
      run: make

    - name: Deploy pages
      run: |
        set -x
        cd ../build
        ls
        git stage --all
        git config --global user.email "git-auto@vstill.eu"
        git config --global user.name "Vladimír Štill's autocommit"
        git status
        git commit -m "Build $(date +'%Y-%m-%d_%H:%M:%S')"
        git push
